18 new step print message
IBM/gauge-web-app-steps pull request #19
Opened 2023-09-18 08:07 UTC by nils-wernecke

New step which prints messages into the Terminal and Report.

`*Print message <Message>`

2023-09-21 11:20 UTC, mario-s approved these changes

2023-09-27 09:41 UTC, derdualist reviewed
Kannst Du den Step noch in der docs/STEPS.md dokumentieren?

2023-09-28 15:38 UTC, mario-s commented on docs/STEPS.md
Wait, the documentation is missing.

2023-09-28 15:39 UTC, mario-s requested changes
Add some documentation please.

2023-09-29 07:55 UTC, mario-s commented on docs/STEPS.md
> +This step will leave the specified message in the report and print it in the terminal.
```suggestion
This step adds the specified message in the report and print it in the terminal.
```

2023-09-29 11:41 UTC, mario-s approved these changes

2023-09-29 11:42 UTC, mario-s commented on docs/STEPS.md
> +This step adds the specified message in the report and print it in the terminal.
```suggestion
This step adds the specified message in the report and prints it in the terminal.
```

2023-09-29 15:37 UTC, mario-s approved these changes

2023-10-02 07:41 UTC, merged

2023-10-02 07:41 UTC, nils-wernecke commented
Closes #18